### ISSUE TITLE
Possibly corrupted block file

### ISSUE THREAD

**Issue by NicolasWent** [Sothatsit/BlockStore#4]
Hello,

I am running BlockStore in a modded server and I get this result : 
[14:25:39 WARN]: java.io.EOFException
[14:25:39 WARN]: 	at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
[14:25:39 WARN]: 	at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
[14:25:39 WARN]: 	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
[14:25:39 WARN]: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
[14:25:39 WARN]: 	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
[14:25:39 WARN]: 	at net.sothatsit.blockstore.chunkstore.ChunkManager.loadStoreSync(ChunkManager.java:275)
[14:25:39 WARN]: 	at net.sothatsit.blockstore.chunkstore.ChunkManager.lambda$loadStore$14(ChunkManager.java:254)
[14:25:39 WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[14:25:39 WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[14:25:39 WARN]: 	at java.lang.Thread.run(Thread.java:748)
[14:25:39 ERROR]: [BlockStore] Possibly corrupted BlockStore file ./world/spawnpaste/block_place_store/x0/z-2_y0.data

Is there any fix to that?

**Comment by Sothatsit** [comment]
> Hello,
> 
> I am running BlockStore in a modded server and I get this result :
> [14:25:39 WARN]: java.io.EOFException
> [14:25:39 WARN]: at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
> [14:25:39 WARN]: at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
> [14:25:39 WARN]: at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
> [14:25:39 WARN]: at java.util.zip.GZIPInputStream.(GZIPInputStream.java:79)
> [14:25:39 WARN]: at java.util.zip.GZIPInputStream.(GZIPInputStream.java:91)
> [14:25:39 WARN]: at net.sothatsit.blockstore.chunkstore.ChunkManager.loadStoreSync(ChunkManager.java:275)
> [14:25:39 WARN]: at net.sothatsit.blockstore.chunkstore.ChunkManager.lambda$loadStore$14(ChunkManager.java:254)
> [14:25:39 WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> [14:25:39 WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> [14:25:39 WARN]: at java.lang.Thread.run(Thread.java:748)
> [14:25:39 ERROR]: [BlockStore] Possibly corrupted BlockStore file ./world/spawnpaste/block_place_store/x0/z-2_y0.data
> 
> Is there any fix to that?

I'm sorry no, there is no fix for this. You will just have to delete that data file and unfortunately everything in it will be lost. Is it possible that your server was forced to stop or crashed while BlockStore was saving?

**Comment by NicolasWent** [comment]
Thank you for your answer.

I don't think that it crashed but it had timed out.

It happended during modded worldedit manipulation. I am using the worldedit mod so I think that happenned when I placed modded/normal blocks with worldedit.

I have deleted the file there were is spawn anyway ^^

But the plugin is still working well when the blocks are placed by hand, the bug only happens with worldedit.
Do you know if I can disable worldedit integration?

**Comment by Sothatsit** [comment]
> Thank you for your answer.
> 
> I don't think that it crashed but it had timed out.
> 
> It happended during modded worldedit manipulation. I am using the worldedit mod so I think that happenned when I placed modded/normal blocks with worldedit.
> 
> I have deleted the file there were is spawn anyway ^^
> 
> But the plugin is still working well when the blocks are placed by hand, the bug only happens with worldedit.
> Do you know if I can disable worldedit integration?

Hi, I've made some changes to allow disabling the worldedit integration of the plugin. Do you think you'd be able to test it to see if it works for you?

https://www.dropbox.com/s/nwa218tpvo3y0h8/BlockStore.jar?dl=0

To disable the worldedit integration you just need to add the following line to your config:
```
hook-world-edit: false
```

Thanks
